### ISSUE TITLE
Formula Fields

### ISSUE THREAD

**Issue by mhofmann06** [ericrsmith35/DatatableV2#10]
Formula fields do not display values in the table.

**Comment by ericrsmith35** [comment]
Please share how you have configured the table.

**Comment by scanlan111** [comment]
For me, I am seeing that when I use a formula field that uses the "HYPERLINK()" formula I am not seeing the link created by the formula.

![Screen Shot 2020-07-22 at 3 21 10 PM](https://user-images.githubusercontent.com/68664763/88224701-fccbd480-cc2e-11ea-8336-bd1c4c65e2f2.png)

**Comment by ericrsmith35** [comment]
I plan on adding translation of HYPERLINK fields to a future release.

**Comment by mhofmann06** [comment]
Scratch my issue. User error. I was getting records in a previous element and didn't explicitly get the formula field I was trying to display in the data table.

**Comment by ericrsmith35** [comment]
@scanlan111 @mhofmann06 The current version will now display these type of formula fields.
https://unofficialsf.com/now-display-rich-text-and-custom-links-and-images-in-datatables/
