### ISSUE TITLE
Subject Column not able to Sort

### ISSUE THREAD

**Issue by Jnew21** [ericrsmith35/DatatableV2#11]
@ericrsmith35  I created a lightning datatable for tasks and the first column is the field Subject.  With V2 this is now a clickable link which is a greate enhancement.  The issue I am having is being able to sort by this column.  All other columns sort without any issues.  Do you know why this might be occuring?  I could find a work around to number the tasks in order to sort, but would like to avoid if I can.  Thanks so much.

**Comment by ericrsmith35** [comment]
I will see if I can reproduce this.

**Comment by Jnew21** [comment]
@ericrsmith35  Were you able to reproduce?  Let me know.  Thanks.

**Comment by ericrsmith35** [comment]
I will try to check this out in the next day or two.

**Comment by Jnew21** [comment]
@ericrsmith35  Just wanted to follow up again and see if you were able to reproduce the issue I was having?  Let me know.  Thanks.

**Comment by ericrsmith35** [comment]
Thanks for pointing this out.  I have fixed the issue with the latest release (v2.40)

**Comment by Jnew21** [comment]
@ericrsmith35  Thank you for fixing so quickly.
