### ISSUE TITLE
Decimals do not get saved

### ISSUE THREAD

**Issue by juhalassila** [ericrsmith35/DatatableV2#14]
Hi! Looks like I have an issue with decimals. I have a number (12,4) field that I can inline edit in datatableV2. 
- Numbers without decimals get saved OK
- Numbers with decimals do not get saved

Pls see attached PPTX for screenshots of 
- values in the datatable 
- properties of the component.

[KK - Salesforce - Datatable BUG - 2020-08-01_0723.pptx](https://github.com/ericrsmith35/DatatableV2/files/5009860/KK.-.Salesforce.-.Datatable.BUG.-.2020-08-01_0723.pptx)

**Comment by juhalassila** [comment]
I think I was able to narrow down this issue to locale settings.

Looks like this component doesn't handle when numbers are presented with a decimal comma (instead of decimal point).

1. Initially observed this issue with Finnish locale setting
- User Profile pic > Settings > My Personal Settings > Language & Time Settings > Locale **Finnish (Finland, Euro)**

2. Switched to **English (United States)**: desimals got saved OK

3. Switched back to Finnish: observed the issue again.

Just to be clear
- I also created a new custom field on Account (type (number(12,4) and planted that on the same screen using the standard Screen Component (Number). That works OK with the Finnish locale setting.

**Comment by juhalassila** [comment]
Aaa... maybe this issue is related to this "feature":

Restrictions
- NOTE: When editing percent fields you are restricted to whole numbers.

I'm assuming that the ability to handle non-integer numbers (and percentages) is on the roadmap. Or is it?

Of course, I desperately need this feature right now.

Unfortunately, I'm not a developer. Therefore, I'm not in a position to contribute in fixing of this issue.

But let me put it this way
- what is the dollar amount that would motivate someone to fix this asap?

**Comment by ericrsmith35** [comment]
I'm looking into this now to see if I can find out why this is happening.

**Comment by juhalassila** [comment]
Just want to let everyone know that I handled our mobile data collection requirement using FormTitan. Therefore, the money is not on the table anymore.

**Comment by ericrsmith35** [comment]
I'm glad you found a solution.
