### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by cklowry** [ericrsmith35/DatatableV2#16]
I've tried twice to install and it has failed both times.

All it really says is :
Status: InProgress 
Status: Completed 
Deployment Complete
Error: errorInternal Server Error 

I have both of the required components installed.

**Comment by ericrsmith35** [comment]
Did you check to see if it actually put the datatableV2 component in your org?

**Comment by ericrsmith35** [comment]
Try this package install for the Datatable Only (No Config Helper)
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3t000001zBG6

**Comment by cklowry** [comment]
That link says it installed but I do not see it in the installed packages or available in flow.

**Comment by cklowry** [comment]
It took about 15 mins, but it finally showed. I've never had that happen before when installing.

THANKS!

**Comment by ericrsmith35** [comment]
The original issue has been resolved by updating the package.xml file.
