### ISSUE TITLE
Custom Geolocation field will prevent flow from loading properly

### ISSUE THREAD

**Issue by issacchern** [ericrsmith35/DatatableV2#19]
Hi Eric, first of all, thanks for this wonderful components. 

I want to report an issue with the geolocation field which I spent hours to find out. It didn't get my attention at first because I wasn't specifically using it in the component. After some time of debugging, I realize that it was because I am using records that automatically store all fields which include the Geolocation__c as well as Geolocation__Latitude__s and Geolocation__Longitude__s.

![image](https://user-images.githubusercontent.com/10298780/90045012-71c58380-dc9c-11ea-9ce3-2f634ea73655.png)
 
As soon as I change the input records, then the flow can continue to work properly.

**Comment by ericrsmith35** [comment]
This is a Salesforce bug that has yet to be addressed.  You will need to manually select the fields you want in your collection and not include the geofield__c.  It is ok to include and use geofield__Latitude__s and geofield__Longitude__s.
