### ISSUE TITLE
Time Displayed Incorrectly

### ISSUE THREAD

**Issue by cklowry** [ericrsmith35/DatatableV2#20]
The new version of the datatable seems to display Time fields in GMT rather than local time. The old version did not do this. As a result all my time values are off by 4 hours.  Is there a setting to adjust?

**Comment by ericrsmith35** [comment]
Thanks for the feedback.  This has been corrected in Version 2.41.

**Comment by cklowry** [comment]
When I try to update to the new version it says I cant do that unless I uninstall the previous version. Which of course I can't do because it's in use in flows.

**Comment by ericrsmith35** [comment]
What is your prior version and which method are you using to install the
new one?

**Comment by cklowry** [comment]
I believe its 2.39 and install without the config helper.

**Comment by ericrsmith35** [comment]
How many flows do you have it in?  I no longer have access to the org that
versions prior to 2.40 were created in.

You could try installing it in a Sandbox then use a change set to move it
to your production org.

**Comment by cklowry** [comment]
LOL.

**Comment by ericrsmith35** [comment]
I can also provide the source code changes to your current version if you
are able to install directly from the source with something like VSCode.

**Comment by cklowry** [comment]
That's a little over my head.  I installed into Sandbox but have no clue what kind of component it is and don't really see it listed. This is more trouble than I had expected.

**Comment by cklowry** [comment]
It's easier just to create a dummy fields that adjust for the 4 hour error. Will probably end up back on the standard datatable since there seems to be no easy way to update going forward. You had a perfectly good install/update plan before. Not sure why it screws things up now.  Thanks for your help though.

**Comment by ericrsmith35** [comment]
Have you also tried the Deploy to Salesforce button in addition to the
package link?

The component consists of a Lightning Web Component called datatableV2 and
2 Apex Classes, SObjectController2 and  SObjectController2Test.

**Comment by cklowry** [comment]
That worked. I got the components over.

 

But sorry, the time fields still don’t work. Matter of fact, it made them dates, the same date for every value no matter what

 

Now it’s not even usable. At least before I could adjust the time.  This I don’t even know what to do with this. It literally has that value no matter what.

**Comment by ChewinChaz** [comment]
Hi Eric, I am also having this same issue.  Was this ever resolved?  Or is it something I messed up on my end?

I am running the latest version and have both classes install as well.

**Comment by ericrsmith35** [comment]
Yes, I have resolved this in Version 2.42.

https://github.com/ericrsmith35/DatatableV2/blob/master/README.md

**Comment by ChewinChaz** [comment]
Perfect!  Thanks Eric you're the man!

**Comment by ChadSeales** [comment]
Hey Eric,

In your fix it appears to be using the User's Geolocation timezone instead of the Timezone set on the User record.
This has presented itself as an issue when our users travel and are in a different timezone than what is set at their user level. All other datetime fields in SF visualize in the User's timezone, whereas the datatable is visualizing on the local time.

**Comment by ericrsmith35** [comment]
I use the date-local format by default. I’ll see if there is any way I
could support an override.
