### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by cklowry** [ericrsmith35/DatatableV2#22]
Is there a way to require at least one row be selected?  I can obviously check on the next screen using a decision, but it would be nice if it could validate onscreen.  Thanks!

**Comment by ericrsmith35** [comment]
It is on my roadmap to add that feature.

**Comment by cklowry** [comment]
Till then would there be a way to add validation to a button? I’m using custom navigation buttons on my screen so could edit the controller if I knew what to look for.

 

CKL

**Comment by ericrsmith35** [comment]
You'll need to look at event.detail.selectedRows in the handleRowSelection
section @ line 893 in datatableV2.js and see if any rows are currently
selected.

**Comment by ericrsmith35** [comment]
This feature has been added in v2.46.
