### ISSUE TITLE
HTML Error when updating

### ISSUE THREAD

**Issue by Jnew21** [ericrsmith35/DatatableV2#24]
@ericrsmith35  I am trying to update the HTML in the datatableV2 and am receiving the following error?  Is this a bug or could I be doing something wrong?  Thanks.

![2020-08-26_13-30-02](https://user-images.githubusercontent.com/61887157/91346721-40c27400-e7af-11ea-9c04-a512da33632d.jpg)

**Comment by ericrsmith35** [comment]
You may have missed something when you made your changes.  Can you share your source code for me to take a look?

**Comment by Jnew21** [comment]
<template>
    <template if:false={showSpinner}>

        
        <template if:true={isOpenFilterInput}>
            <div style="height: 40px;">
                <section role="dialog" tabindex="-1" aria-labelledby="modal-heading-01" aria-modal="true" aria-describedby="modal-content-id-1" class="slds-modal slds-fade-in-open">
                    <div class="slds-modal__container">
                        <header class="slds-modal__header slds-modal__header_empty">
                            <button class="slds-button slds-button_icon slds-modal__close slds-button_icon-inverse" title="Close" onclick={handleCloseModal}>
                                <lightning-icon icon-name="utility:close" alternative-text="close" variant="inverse" size="small"></lightning-icon>
                                <span class="slds-assistive-text">Close</span>
                            </button>
                        </header>
                        <div class="slds-modal__content slds-p-around_medium" id="modal-content-id-1">
                            <lightning-input 
                                type={inputType}
                                formatter={inputFormat} 
                                label={inputLabel} 
                                value={columnFilterValue} 
                                onchange={handleChange}
                            >
                            </lightning-input>
                        </div>
                        <footer class="slds-modal__footer">
                            <button class="slds-button slds-button_neutral" onclick={handleCloseModal}>Cancel</button>
                            <button class="slds-button slds-button_brand" onclick={handleCommit}>Save</button>
                        </footer>
                    </div>
                </section>
                <div class="slds-backdrop slds-backdrop_open"></div>
            </div>
        </template>

        
        <div style={tableHeight} class={borderClass}>
            <lightning-datatable
                data={mydata}
                columns={columns}
                key-field={keyField}
                sorted-by={sortedBy}
                sorted-direction={sortedDirection}
                max-row-selection={maxRowSelection}
                selected-rows={selectedRows}
                hide-checkbox-column={hideCheckboxColumn}
                suppress-bottom-bar={suppressBottomBar}
                onsort={updateColumnSorting}
                oncellchange={handleCellChange}
                onsave={handleSave}
                oncancel={cancelChanges}
                onheaderaction={handleHeaderAction}
                onrowselection={handleRowSelection}
                onrowaction={handleRowAction}
                onresize={handleResize}
            >
            </lightning-datatable>
        </div>

        
        <template if:true={isConfigMode}>
            <div>
                </br>
                <p><span class="slds-text-heading_medium">Click the attribute to load the clipboard with the value to be pasted into your datatableV2 parameter.</span></p>
                </br>
            </div>
            <div class="slds-m-horizontal_medium">
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Fields:</span></p>
                    <lightning-pill label={columnFieldParameter} onremove={handleRemove} onclick={handleCopyFields}></lightning-pill>
                </div>
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Alignments:</span></p>
                    <lightning-pill label={columnAlignmentParameter} onremove={handleRemove} onclick={handleCopyAligns}></lightning-pill>
                </div>
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Edits: 
                        <lightning-button
                            label="Select All Columns" variant="brand-outline" onclick={handleSelectAllEdit} class="slds-float_right">
                        </lightning-button>
                    </span></p>
                    <lightning-pill label={columnEditParameter} onremove={handleRemove} onclick={handleCopyEdits}></lightning-pill>
                </div>
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Filters: 
                        <lightning-button
                            label="Select All Columns" variant="brand-outline" onclick={handleSelectAllFilter} class="slds-float_right">
                        </lightning-button>
                    </span></p>
                    <lightning-pill label={columnFilterParameter} onremove={handleRemove} onclick={handleCopyFilters}></lightning-pill>
                </div>
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Labels:</span></p>
                    <lightning-pill label={columnLabelParameter} onremove={handleRemove} onclick={handleCopyLabels}></lightning-pill>
                </div>
                <div class="slds-box slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Column Widths:
                        <lightning-button
                            label={roundValueLabel} variant="brand-outline" onclick={handleRoundWidths} class="slds-float_right">
                        </lightning-button>
                    </span></p>
                    <lightning-pill label={columnWidthParameter} onremove={handleRemove} onclick={handleCopyWidths}></lightning-pill>
                </div>
                <div class="slds-box slds-box_x-small slds-theme_alert-texture slds-m-vertical_xx-small">
                    <p><span class="slds-text-heading_small">Clipboard Contents:</span></p>
                    <input disabled class="my-clipboard slds-input"/>
                </div>               
            </div>
        </template>

    </template>

    
    <template if:true={showSpinner}>
        <lightning-spinner alternative-text="Loading" size="medium"></lightning-spinner>
    </template> 

</template>

**Comment by ericrsmith35** [comment]
Which line in your code is #97?

**Comment by Jnew21** [comment]
<div style={tableHeight} class={borderClass}>

**Comment by AndyHaas** [comment]
This is just a VS code issue. 

The error you're getting is from vscode's CSS validator. style={tableHeight} works in LWC but it violates a rule in the CSS validator that vscode runs.

If you don't need/use the validator and you want to get rid of the errors, you can disable the validator entirely by going to File > Preferences > Settings > Extensions > CSS and unchecking the Validate checkbox. Otherwise you'll have to find the specific rules being violated and disable them.

**Comment by ericrsmith35** [comment]
Thanks Andy.
