### ISSUE TITLE
Output Selected Rows - No returned values and no error

### ISSUE THREAD

**Issue by moahultin** [ericrsmith35/DatatableV2#27]
We have an issue when using the Output Selected Rows - The component breaks without any error after selecting rows and clicking next. What I can see it works for opportunity but in my case not for Asset. 

If no rows are selected the component continues as expected.

This worked before (v 2.31) but can no longer get it to work. 

![image](https://user-images.githubusercontent.com/10611772/92807517-3e6d3600-f3bb-11ea-8898-f2dfbd0608b5.png)

After clicking next: Breaks, No debug, no error. Expected output is a new screen with data table showing selected lines. 
<img width="1665" alt="Screenshot 2020-09-10 at 23 13 55" src="https://user-images.githubusercontent.com/10611772/92809620-1383e180-f3bd-11ea-961f-d44cd70aa246.png">

No lines selected: Behaves as expected. 
<img width="1665" alt="Screenshot 2020-09-10 at 23 28 36" src="https://user-images.githubusercontent.com/10611772/92810137-8f7e2980-f3bd-11ea-9ec5-79160c4708c5.png">

Any ideas what could be causing this?

**Comment by ericrsmith35** [comment]
Does the Asset object have any Geolocation fields?

**Comment by moahultin** [comment]
Yes It does.. Is this causing the issue? Any workaround? Thanks for you fast reply!

**Comment by ericrsmith35** [comment]
This is a Salesforce bug that has not been addressed yet.  For some reason,
objects with geolocation fields cause a problem with the datatable
component.  You could try to manually define your output variables for the
component and see if that makes any difference.

**Comment by moahultin** [comment]
Thanks! Got it working when the Asset collection did not store the geolocation fields.
