### ISSUE TITLE
When using Apex-Defiend Object, it is only return back the first option

### ISSUE THREAD

**Issue by wilsonwong13** [ericrsmith35/DatatableV2#29]
Currently following this guide - https://ericsplayground.wordpress.com/how-to-use-an-apex-defined-object-with-my-datatable-flow-component/

When I select any choice, it is currently only returning the first option as outputselectedrows.

**Comment by wilsonwong13** [comment]
I figure out the issue. The way the code works is that it will look at the Id field between the selected row and the datatable. Just add an Id Field and have that as unique characters for each data

**Comment by pyao-bwc** [comment]
Hi @wilsonwong13 , thanks for figuring this out, it saved me a lot of time!

In case others run into it, I found that the Key Field is case sensitive. So my field is defined in my Apex type as this:
```
    public Id id;
```
And it wouldn't work if this configuration was ``Id``, it has to be like this (and has to be set):
![image](https://user-images.githubusercontent.com/23371412/96641724-27dbc800-12f3-11eb-8b0a-abb6e5f393c6.png)
