### ISSUE TITLE
Inline editing not working

### ISSUE THREAD

**Issue by ddefosse** [ericrsmith35/DatatableV2#33]
hi,

Inline editing not working
Does anyone else have this problem?

**Comment by ericrsmith35** [comment]
Which version do you have installed?  What is the field type that you are having a problem with?

**Comment by ddefosse** [comment]
I installed the version 2.44
i have problem with any field type.
on no field the small pen appears

**Comment by ericrsmith35** [comment]
What is the value of your Column Edits attribute?

**Comment by ddefosse** [comment]
I tested with

All
1: true
fieldNameApi: true

but none of these combinations worked

**Comment by ericrsmith35** [comment]
Are you available for a quick screenshare so I can see what is happening?

**Comment by ddefosse** [comment]
yes of course but can we continue to exchange in writing because my oral English is really not good?

 

De : Eric Smith <notifications@github.com>
Répondre à : ericrsmith35/DatatableV2 <reply@reply.github.com>
Date : mardi 22 septembre 2020 à 14:49
À : ericrsmith35/DatatableV2 <DatatableV2@noreply.github.com>
Cc : ddefosse <ddefosse@koobeto.com>, Author <author@noreply.github.com>
Objet : Re: [ericrsmith35/DatatableV2] Inline editing not working (#33)

 

Are you available for a quick screenshare so I can see what is happening?

**Comment by ddefosse** [comment]
yes of course but can we continue to exchange in writing because my oral English is really not good?

**Comment by ericrsmith35** [comment]
No problem - I'll send an invite

**Comment by ericrsmith35** [comment]
Fixed in v2.45
