### ISSUE TITLE
Error on deploying  Datatable Configuration Helper Flow

### ISSUE THREAD

**Issue by raulramoso** [ericrsmith35/DatatableV2#38]
Hello,

Deployment failed for  Datatable Configuration Helper Flow. Here the error:

apexColFieldDescriptors (Variable) - "apexClass" is invalid. Provide the API name of an Apex class that includes an Apex data type supported in flows.

**Comment by ericrsmith35** [comment]
Did you install the required components first?
Flow Base Components (https://unofficialsf.com/introducing-flowbasecomponents/)
Dual List Box (https://unofficialsf.com/duallistbox/)

Do all of the current Apex Classes in your org pass?

**Comment by raulramoso** [comment]
Hello Eric,

No, I did not. I was assuming that components were installed when deploying.

I will install them and let you know.

Thank you
Raul Ramos

**Comment by Mar5929** [comment]
@raulramoso did you figure this out? I am getting the same error. I have the two prerequisite packages installed too.

**Comment by raulramoso** [comment]
Hello Michael,

We are not using SF in our company anymore. Honestly I do not remember the details on this troubleshooting, and not have access to SF anymore.

Raul Ramos
