### ISSUE TITLE
Lookup field url inserts object from the records being retrieved instead of the object the lookup is to

### ISSUE THREAD

**Issue by muel8192** [ericrsmith35/DatatableV2#39]
I have a custom object, Access_Request__c, and it has a lookup field, to the User, on it. The component correctly displays the User name, but the hyperlink brings you to this URL: /lightning/r/Access_Request__c/0053h000001cj2FAAQ/view  However, I would expect it to bring me to this URL: /lightning/r/User/0053h000001cj2FAAQ/view  The ID in the URL is the correct user ID. Do I have the component set up wrong?

**Comment by muel8192** [comment]
Also, as a wish list kind of thing, I am using this in a community, so the base URL is bringing you to the community, not production. That means that if it did resolve to the User it would point to the profile, not the User record in the internal org. It would be really nice to be able to specify the base URL that the lookup field should resolve to. At least the right ID shows up, so they can grab it and throw it on the internal org. For my purpose, what the community user needs is the User Details, not the Profile.

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
