### ISSUE TITLE
Error while trying to deploy

### ISSUE THREAD

**Issue by jeanadrc** [ericrsmith35/DatatableV2#42]
Hello,

I have an issue to deploy your component like this : 
Deployment Started
Status: Queued 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: Completed 
Deployment Complete
Error: errorInternal Server Error
We deployed your compenent 6 months ago but we need to update it in our org in order to use the new features.
So actually we don't know how to do it without removing it from our org and reinstall, the problem with this way is that it will take a long time to delete it because we need to modify all the flows where we used your component.
Do you have any idea how to do it quickly.

Thanks.

**Comment by ericrsmith35** [comment]
You will first need to install the most recent version of the Flow Base
Components.

**Comment by rneel** [comment]
@ericrsmith35 
I'm having the same issue, however, I've already installed all the prerequisites from what I can see:
![image](https://user-images.githubusercontent.com/21131134/97213782-7a583100-1798-11eb-8cd6-a8d1dd0796c4.png)
![image](https://user-images.githubusercontent.com/21131134/97213800-817f3f00-1798-11eb-8ef0-21a84b385730.png)

**Comment by ericrsmith35** [comment]
A couple of other reasons you might see that error is that you have other
Apex Test Classes in your org or you have validation rules on Account that
cause my test classes to fail when trying to create a dummy Account for the
test class.

You could try temporarily deactivating your Account validation rules and
see if that makes a difference.

Eric

**Comment by rneel** [comment]
@ericrsmith35 

Unfortunately, running the deploy after turning off all the Account validation rules yielded the same results.

**Comment by ericrsmith35** [comment]
Here is a temporary version for v2.47 that does not have the Helper Flows.  See if using the install base components link, then the Deploy to Salesforce button helps.

https://github.com/ericrsmith35/DatatableV2/tree/tempfix

**Comment by mkolodner** [comment]
Same issue. Prerequisites are installed and I turned off Account validation rules. But I'm getting this error (for all 6 Apex classes:
System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Failed to create Account for Contact TestFname TestLname. Record Type ID: this ID value isn't valid for the user: 0120y000000YPbjAAG: [] 
Stack Trace: Class.DisableChatterDeletesTestSuite.insertDummyContact: line 18, column 1 Class.DisableChatterDeletesTestSuite.testFeedCommentDelete: line 120, column 1

What record type Id is it trying to insert?
