### ISSUE TITLE
Error with multi-picklist after variable assignment

### ISSUE THREAD

**Issue by AndreaDan1004** [ericrsmith35/DatatableV2#44]
Hi, I faced an exception when trying to list records in a table with multi-picklist as column.

**Steps to reproduce:** 
- Get record of an object with a multi-picklist field and save it in a record variable ("automatically stores all fields" is fine)
- Have a screen that allows the user to select items in the multi-picklist
- Assign user-selected values to the multi-picklist field in the record variable
- Call the table component in another screen with multi-picklist as column

**Error**
This page has an error. You might just need to refresh it. [Cannot read property 'message' of undefined] Failing descriptor: {markup://c:datatableV2}

**Notes**
I wasn't facing this issue using the previous version when multi-picklist selections were shown as API names instead of labels.

**Comment by ericrsmith35** [comment]
Please share your flow or some screenshots of how you have it configured and I'll take a look.

**Comment by AndreaDan1004** [comment]
[Screenshots.zip](https://github.com/ericrsmith35/DatatableV2/files/5383135/Screenshots.zip)
I created a simple flow in order to repro the issue. Please find screenshots attached. Thanks a lot for your help!

**Comment by AndreaDan1004** [comment]
[Screenshots2.zip](https://github.com/ericrsmith35/DatatableV2/files/5384657/Screenshots2.zip)
Here the screenshots of missing blocks and flow executed in debug mode. Note: the Get_Account step has an hard-coded id in the query, but it's only for repro purpose. Thanks again for your help!

**Comment by ericrsmith35** [comment]
See if it makes any difference if you remove the , and the / from the picklist values.

**Comment by AndreaDan1004** [comment]
I just made a test removing "," and "/" but faced same error as before.

**Comment by ericrsmith35** [comment]
Please post an issue here if this is still a problem with the current release (3.0.10)
https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/datatable
