### ISSUE TITLE
Allow Clear Button on Radio Button List

### ISSUE THREAD

**Issue by jeffolmstead** [ericrsmith35/DatatableV2#45]
First off, excellent solution, thanks for sharing. I had the need to be able to clear the Radio Button selection (e.g. allow someone to de-select what they had picked) and was able to do so by overriding datatableV2.js line 1009 from this:

`
this.showClearButton =  (this.tableData.length == 1 && this.numberOfRowsSelected == 1)
`

to this:

`
this.showClearButton = this.numberOfRowsSelected == 1 && (this.tableData.length == 1 || this.singleRowSelection);
`

This now gives this effect when a radio button is selected:

![image](https://user-images.githubusercontent.com/1848585/96140070-86f1a500-0ecd-11eb-81e8-a7a32674ef31.png)

I was wondering if this might be useful to incorporate into the solution as others might have the need to remove their selected row while using radio button view.

**Comment by ericrsmith35** [comment]
Thanks @jeffolmstead - I'll be including this in the next release.
