### ISSUE TITLE
Have handleClearSelection Clear outputSelectedRowsString Also

### ISSUE THREAD

**Issue by jeffolmstead** [ericrsmith35/DatatableV2#46]
Currently, handleClearSelection in datatableV2.js only clears out the outputSelectedRows (e.g. sets to empty array). However, I utilize the string output so could we also add this line in:

`this.outputSelectedRowsString = "";`

This changed worked in my environment where I am not using strongly typed objects. Let me know if you have any questions.

**Comment by ericrsmith35** [comment]
Good feedback.  I will make the changes.

**Comment by ericrsmith35** [comment]
I have included this update in the current version (3.1.1) of the Datatable component.
