### ISSUE TITLE
Cannot inline edit fields on apex-defined table

### ISSUE THREAD

**Issue by ohadios** [ericrsmith35/DatatableV2#49]
When I enabled inline edit on one of the columns in my apex-define table, everything looks good - except I cannot find any way to get those values out of the screen.
When clicking 'Save', the values disappear from the screen.
I attempted to suppress the save button, but the values are not passed out through the output string.

**Comment by ericrsmith35** [comment]
What is the field type you are trying to edit?

**Comment by ohadios** [comment]
> What is the field type you are trying to edit?

Number field - decimal.

**Comment by ericrsmith35** [comment]
Do text and integer fields work when you edit them?

**Comment by ohadios** [comment]
> Do text and integer fields work when you edit them?

Just tried to both - no luck :/

**Comment by ericrsmith35** [comment]
Are you checking the contents of the Output Edited Records attribute after selecting Next from the datatable Flow screen?

**Comment by ohadios** [comment]
> Are you checking the contents of the Output Edited Records attribute after selecting Next from the datatable Flow screen?

I just tried - the "Output Edited Rows (User Defined)" returns an empty list - whether I just 'ignore' the save button, or if I suppress it. Clicking save still just clears the values.

The "Output Selected Rows (User Defined)" returns the selected rows, but without the edited value.

**Comment by ericrsmith35** [comment]
I ran a number of tests and I'm still not able to reproduce your issue.  Can you point me to a repository where you have your flow and apex classes so I can take a closer look?

**Comment by ohadios** [comment]
> I ran a number of tests and I'm still not able to reproduce your issue. Can you point me to a repository where you have your flow and apex classes so I can take a closer look?

I guess I'm doing something wrong - that's encouraging :)
I just put the source in this git:
https://github.com/ohadios/dataTableFlow

There are two datatables in this flow. It's the second one, named: lotWrappers that is using the custom apex object.

**Comment by ohadios** [comment]
Hi Eric - I've not had much luck trying to figure this out... have you had a chance to look into my repo?

**Comment by arnaudvdvk** [comment]
@ericrsmith35 @ohadios Hello, I'm facing the same issue. I hope we can find a solution for that.
Thanks !

**Comment by ericrsmith35** [comment]
I have not yet had a chance to look at this.  I hope to take a look this
weekend or next.

Eric Smith

**Comment by arnaudvdvk** [comment]
@ohadios I had the same issue but I found the cause. It is a config reason. You need to change the "Key Field". You need to put a field that is unique. I'm working on Product Items, so I put "Product2ID".

I hope it helps.

@ericrsmith35  FYI

**Comment by ericrsmith35** [comment]
Thanks.

**Comment by ohadios** [comment]
Thank you @arnaudvdvk ! will check it out next time I have a use-case...
I took a different approach using objects for now - but I may roll back to using apex objects.
