### ISSUE TITLE
Suggestion - Open links on subtabs

### ISSUE THREAD

**Issue by brunomesquita22** [ericrsmith35/DatatableV2#51]
Hi guys, how u doing?

Is it possible to (in a future version) permit changing the behaviour when the user clicks in a SObject’s ‘Name’ field?

Today the behaviour is opening a new tab in browser, but for users that works in Omnichannel or attending Live Agent requests, that is not a good thing. 

Opening SF in a new tab can end on-going chats or causing troubles in omnichannel functioning.

Beeing able to open these records in a subtab would fix this.

**Comment by JodieM** [comment]
Yes, I would like this too please.

**Comment by yaminm** [comment]
Can be very helpful. My customer drops the suggestion to use it only because of it since we are using Console.

**Comment by yaminm** [comment]
Meanwhile, for those who can't wait you can change it by yourselves just change line 806 like in this printscreen. In case you would like to have the same EXP in other lookups change 816 too.

![image](https://user-images.githubusercontent.com/6897250/105699435-07359680-5f10-11eb-9124-682173726ebe.png)

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
