### ISSUE TITLE
First record in Selected or Edited collection variables is NULL

### ISSUE THREAD

**Issue by Windyo** [ericrsmith35/DatatableV2#52]
This is a non-breaking bug as Salesforce ignores this line on DML.

- Do a dtatable
- store edited records in a coll var
- store selected records in a coll var
- loop through oe and the other
- check details of loop in Debug mode

>> The first result is always a fully null record with no data. This doesn't prevent insert or update, and as such is non-breaking, but does show up when doing screens that iterate over selected components.

Desired:
>> only selected or edited records show up - NULL is omitted

**Comment by ericrsmith35** [comment]
I'm not able to reproduce this in the current release (3.0.10)
For current Source, see: https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/datatable
