### ISSUE TITLE
Object Name Link is Missing Characters from Domain Name

### ISSUE THREAD

**Issue by TiminMaine** [ericrsmith35/DatatableV2#54]
Hello, What would cause the URL of a link from a Record in the DataTable to be missing four characters in the middle of the URL?  It is not happening in one of my Sandbox Orgs but it is happening in another.  The url should be something like "https://orgname--sandbox2.lightning.force.com/", but the link for the Contact Record is coming out like "https://orgnamandbox2.lightning.force.com".  

p.s. this is my first post to GitHub so if this is not the right place to put something like this, let me know. Thanks very much.
p.p.s. I really appreciated your demo on NE Dreamin, and I'm loving working the DataTable.

**Comment by ericrsmith35** [comment]
Temporary fix here.
https://github.com/ericrsmith35/DatatableV2/tree/tempfix

This fix will also be incorporated in the next official release.
