### ISSUE TITLE
Table position

### ISSUE THREAD

**Issue by rajesh-k** [ericrsmith35/DatatableV2#55]
The data table keeps moving up a line or 2 when cell edit operation is invoked by clicking the pencil icon and all rows are selected. The attached screenshots better explain the problem. Look at them side by side (position 1 and 2). The second table moved up because of clicking the edit/pencil icon. Is this an issue in the data table or the way  I have embedded the data table?

![Datatable-position-1](https://user-images.githubusercontent.com/3512420/97793898-ae27c200-1baf-11eb-959a-704fb2fd6b38.jpg)
![Datatable-position-2](https://user-images.githubusercontent.com/3512420/97793899-b08a1c00-1baf-11eb-99fc-705de0b28731.jpg)

**Comment by ericrsmith35** [comment]
This is not caused by the datatable component itself, but by the internal code used by Salesforce to support the table and editing.
