### ISSUE TITLE
How to get Richtext working

### ISSUE THREAD

**Issue by JodieM** [ericrsmith35/DatatableV2#56]
Is there some trick to getting rich text to work? 
I tried to show the Body of AccountFeed in the datatable and it came out as raw HTML.

**Comment by ericrsmith35** [comment]
Body is not a TextArea(Rich) field.  It is a regular TextArea field.  The system has another boolean field in the Feed record called isRichText.  

The datatable doesn't work directly on TextArea fields.  In a custom object, you could create a Text Formula field that contains the contents of a TextArea (Rich) field to have it display with formatting in the datatable.
