### ISSUE TITLE
Save button doesn't appear until the focus is lost

### ISSUE THREAD

**Issue by rajesh-k** [ericrsmith35/DatatableV2#58]
Take a look at the attached image. The save button does NOT appear in the grid until I tab out or click on something else. Is it possible to activate the Save button upon making a selection in the grid?

![MissingSaveButton](https://user-images.githubusercontent.com/3512420/98625798-35b6b480-22c5-11eb-8ca3-91827d77841a.jpg)

**Comment by ericrsmith35** [comment]
This is standard behavior of the base datatable component.  You do have the option to suppress the footer and immediately Save on a Cell Change.
