### ISSUE TITLE
Lookups to a User showing their Id instead of their name for some users

### ISSUE THREAD

**Issue by Catmacey** [ericrsmith35/DatatableV2#6]
Hi. 

I have a datatable (v2 Summer 2020) that amongst other things contains a lookup to Users in my Org.

For myself and other admins the lookup is working correctly and shows the User's Name.  For other users in my Org the table only shows the user Id.

Using Firefox Debugger I can see that the response back from the the call to SObjectController2 contains an empty `dataMap` and that the rowData contains just a `Person__c` key containing the Id for the User whereas when run as my admin user the `dataMap` contains a `User` key containing all the relevant Users data plus the `rowData` contains an additional `Person__r` key that also contains all the User data.

Is this a permissions thing? Do I need to give my user rights to execute something?

**Comment by ericrsmith35** [comment]
That certainly looks like a permissions issue.

**Comment by Catmacey** [comment]
It appears that if my lookup field is `visible` but `read-only` for the current user then they do not get the Names (Lookup data is not populated) whereas if I remove the read-only field-level security then they do get the lookup data in the response from `SObjectController2`.

So that's a sort of fix... As long as that doesn't cause me troubles elsewhere.

I'd really like to work out why it doesn't work as it does seem odd that a read-only field can't be "expanded" to show the names as that is such a great feature.

Thing is I'm not really sure where to start. 
It looks like the issue revolves around the call to Schema.DescribeFieldResult.isUpdateable() [SObjectController2.cls line 117](https://github.com/ericrsmith35/DatatableV2/blob/9ee1dfa3aed19cab763bbac512d54266e0dc251f/force-app/main/default/classes/SObjectController2.cls#L117). I can see that a read-only field would return false but I have no idea what the implications are if I were to change or remove that test...  
You obviously added that for a good reason as noted in v1.2 

Is there something that can be done? here or is the simplest answer just to change the field to not be read-only and live with it?

Many thanks for your help.
And many more thanks for creating some truly excellent components.

**Comment by ericrsmith35** [comment]
That check is there because the feature requires that a Master/Detail
relationship has to be reparentable.
