### ISSUE TITLE
Master-Detail Lookup not displaying the field name and link but the record id as text

### ISSUE THREAD

**Issue by jdamiens** [ericrsmith35/DatatableV2#60]
Hi Eric,

First, thank you very much for this fantastic component that is saving so much of my admin time.

I'm running into an issue displaying a custom object collection in the datatable where the lookup field to the parent record is displayed as a recordId text instead of record name and link.

It was working perfectly until today, the only root cause I can imagine is that there is another standard lookup field to the same object as the parent that have been added lately. But when I add this lookup field to the datatable, it works fine. The issue is only on the master-detail. of that particular object.

Screenshot here below, column "AE".
Best regards
![Screenshot 2020-11-24 at 18 18 00](https://user-images.githubusercontent.com/23356310/100129138-7136ae80-2e81-11eb-8672-f04104653601.png)

**Comment by ericrsmith35** [comment]
The relationship has to be "reparentable" for the link to work.

**Comment by jdamiens** [comment]
Thanks for the quick answer. It is solved.
