### ISSUE TITLE
Filtering on a Boolean column

### ISSUE THREAD

**Issue by rorywebbertc** [ericrsmith35/DatatableV2#61]
I'm having issues getting filtering working on a checkbox column. If I set the filter value to True then the non-checked items are not displayed, as expected. However, setting the Filter value to False and the table displays no row at all, where I am expecting the records where the checkbox is unchecked to be displayed.

**Comment by ericrsmith35** [comment]
This has been corrected in the current version (3.1.1) of the [Datatable](https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/) component.
