### ISSUE TITLE
Edit more than 20 records, screen freezes after clicking Next button 

### ISSUE THREAD

**Issue by samithp** [ericrsmith35/DatatableV2#63]
When the user tries to edit bigger number of records  (around 20) the function doesn't work, after clicking Next the browser freezes,

**Comment by ericrsmith35** [comment]
I'd like to try and narrow this down and provide any possible fixes.  Can you provide a few more details please?  What object are you displaying, how many records, how many columns?  What types of fields are being edited?

**Comment by samithp** [comment]
Thanks  @ericrsmith35 

What object are you displaying - **Assets**
how many records - **180 records**
how many columns - **7 columns** 
What types of fields are being edited- **boolean(checkbox)**

I have attached screenshot of datatable 

![image](https://user-images.githubusercontent.com/75673394/101649921-b3442080-3a3b-11eb-9ec8-3f2e11bf0453.png)

let me know if you need anything else. and thank you so much for the attention

**Comment by lindyrogers** [comment]
We are having this same issue. 
What object are you displaying - Custom Object
How many records - varies, it froze today with 26 records
How many columns - 6 displayed, 4 being edited
What types of fields are being edited - Currency(18, 0) & Text Area(255)

**Comment by samithp** [comment]
@ericrsmith35 Wishing you happy new year
Is there any update on this?

Thanks in advance 
Samith

**Comment by Windyo** [comment]
@ericrsmith35 hey :)
Same issue here.

Couple notes:

- Seems to happen on any object (tried three)
- seems to happen with varying number of columns displayed (tried between 4 and 8) and edited (tried between 1 and three)
- seems to happen on multiple column types (tried numerical as well as boolean and text)

In all above cases the table not only froze, but actively froze the browser completely for non-powerful computers, and froze the tab at least on more powerful ones.

Issue has been reproduced with the same exact characteristics on DataTableV3

**Comment by Windyo** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jmeinen** [comment]
@ericrsmith35 You mentioned that you've given Salesforce a reproducible example. Does this mean that the problem is, according to you, in a standard component used by DatatableV2? Can you explain more? 

Is there any progress on this or a suitable workaround?

Thanks for your support!

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
