### ISSUE TITLE
I see all the API names when there is no records to show. just in version 2.46. is there a way to show only the text "Empty Table"?

### ISSUE THREAD

**Issue by BenKeshet** [ericrsmith35/DatatableV2#65]
![pasted image 0 (1)](https://user-images.githubusercontent.com/76433669/102775716-0f8d3580-4396-11eb-98a8-7ba4c8b62682.png)

![pasted image 0 (2)](https://user-images.githubusercontent.com/76433669/102775756-22a00580-4396-11eb-982f-d5c7ffdabbff.png)

**Comment by BenKeshet** [comment]
There is a solution here? how do I remove the API names when there is no records?

**Comment by ericrsmith35** [comment]
Are you looking for nothing to display or just a notice that it is an empty
table?

**Comment by BenKeshet** [comment]
I want it to be like the picture above. display only the "Empty Table" text

**Comment by AlexKasper** [comment]
I've noticed the same issue. If the collection is empty, the table name and field API names are displayed which is potentially confusing to an end user.

**Suggestion:** If _Configuration Mode?_ is FALSE, an empty collection displays only the **Table Label** and **Table Icon** (similar to standard related list behavior), otherwise If _Configuration Mode?_ is TRUE, display field API names.

**Comment by ericrsmith35** [comment]
This will be fixed when v3.0.5 is released in the next few days.

**Comment by BenKeshet** [comment]
Thanks!
Next few days it means next week more or less?

**Comment by ericrsmith35** [comment]
Yes, should be before the end of next week.

**Comment by BenKeshet** [comment]
Thanks alot!

**Comment by BenKeshet** [comment]
Hi!
Is it deployed already?

Thanks

**Comment by AlexKasper** [comment]
@BenKeshet Heads up: _End of next week_ would be this coming Sunday at the earliest and it could be later—_or never!_

A gentle remember this is _not_ a commercial product and is being offered as-is for testing only—and not guaranteed for use in production. There is no promise it will continue to work and no obligation from anyone to fix it on any time schedule if it breaks or doesn't function for some reason.

If this is being used in production environments, you could have problems one day with nowhere to go. Always have a backup plan that doesn't use this! Please be careful!

**Comment by ericrsmith35** [comment]
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
