### ISSUE TITLE
Ability to hide update selected items in a column row

### ISSUE THREAD

**Issue by medhaniesfdc** [ericrsmith35/DatatableV2#72]
Hi there, I am wondering if there is a way to hide update selected items in a column row, for instance when a flow clicks a row in a column, they are given the option to update all selected items, can we remove that to only permit just one.

<img width="1280" alt="Screen Shot 2021-02-28 at 10 44 21 AM" src="https://user-images.githubusercontent.com/79806518/109429734-32e5e980-79b2-11eb-904d-3f7fa55ec9f3.png">

**Comment by AlexKasper** [comment]
·          The selection column can be multi-select (Checkboxes), single-select (Radio Buttons), or hidden.

**Comment by ericrsmith35** [comment]
This is a built in function of the base datatable in Lightning and can not be overridden.  If multiple rows are selected, that option will always appear.
