### ISSUE TITLE
Rich Text Field Displayed

### ISSUE THREAD

**Issue by DjibrilEE** [ericrsmith35/DatatableV2#8]
Hi Eric,

Thanks so much for all the fantastic work you do! I wouldn't so much classify this as an issue but a possible enhancement. I have a requirement to include a rich text field in the data table as a column. As you probably know, the data displayed includes the HTML tags from the rich text field. Is there any way to render without?

Thanks again!

**Comment by ericrsmith35** [comment]
Currently there is no support for rich text but that could be a future
enhancement.
