### ISSUE TITLE
User Defined Object JSON returns the same row data once per row selected

### ISSUE THREAD

**Issue by stephenpstanley** [ericrsmith35/DatatableV2#9]
When using a user defined APEX input String, the input string is:

[{"Registration_Status":"Waitlisted"},{"Registration_Status":"Registered"},{"Registration_Status":"Attended"},{"Registration_Status":"No show"},{"Registration_Status":"Withdrawn"}]

This presents a list for selection of
[] Waitlisted
[] Registered
[] Attended
[] No show
[] Withdrawn

If I assign the **Output Selected Rows (User Defined)** to a text variable then if all options are selected, the output JSON string is:
[{"Registration_Status":"Waitlisted"},{"Registration_Status":"Waitlisted"},{"Registration_Status":"Waitlisted"},{"Registration_Status":"Waitlisted"},{"Registration_Status":"Waitlisted"}]

If I just select one option, then regardless of which option is selected, it returns:
[{"Registration_Status":"Waitlisted"}]

It only ever returns the first option and returns it multiple times - once for each option that is selected

**Comment by ericrsmith35** [comment]
The User Defined option requires a separate Apex Class with the object
definition.  You might want to try using QuickChoice for your selection
instead.

https://unofficialsf.com/quick-choice-improved-picklists-and-radio-buttons-for-flow/

**Comment by stephenpstanley** [comment]
OK thanks @ericrsmith35 I'm trying to avoid as much APEX as possible since this is work being done to be handed over to ta third party who has no dev skills.  I also need the ability to select multiple checkboxes.  I may have to do some horrible hacky flow steps instead :-(
